# Makefile
# Lab: 2
# Class: Operating Systems
# Semester: FALL 2021
# Author: Pablo Ruiz

CC=g++

all: part1 part2

part1: part1.cpp
	$(CC) -o part1 part1.cpp -lpthread -lrt

part2: part2.cpp
	$(CC) -o part2 part2.cpp -lpthread -lrt
